if(!U())location.replace('/auth#login');
topbar();
const SC=120;let R,TID,stf=[],subs=[],ls=[],ts=[],cs=[],ads=[],bks=[],ups=[],sols=[],fls=[],qzs=[],cc=[],CCN={},LD=0,BOOT=true,usFull=false,OV={},tab=window.TAB||'c',P=null,QI=[],QT='',us=[],OL=0,apA=[],apS='pending',apK='all',TRT={};
const TURL={o:'/staff',c:'/staff/content',g:'/staff/subjects',t:'/staff/teachers',ap:'/staff/applications',x:'/staff/users',s:'/staff/support',n:'/staff/notifications',qa:'/staff/questions',rv:'/staff/reviews',a:'/staff/ads',b:'/staff/books',u:'/staff/updates',ab:'/staff/about'};
const tsub=t=>(t&&t.subject_ids)||[],tFor=sid=>ts.filter(t=>tsub(t).includes(+sid)),tlid=t=>(t&&t.lesson_ids)||[],tForL=l=>ts.filter(t=>tsub(t).includes(+l.subject_id)&&(!tlid(t).length||tlid(t).includes(+l.id))),myT=()=>ts.find(t=>t.id==TID),okL=l=>R=='admin'||!tlid(myT()).length||tlid(myT()).includes(+l.id),SV=()=>R=='admin'?subs:subs.filter(s=>tsub(ts.find(t=>t.id==TID)).includes(s.id));
const fail=async r=>{const t=await r.text().catch(()=>'');let j={};try{j=JSON.parse(t)}catch(_){}const code=j.code||'';say(/23505|duplicate/i.test(t)?'الرابط (slug) مستخدم بالفعل — غيّره':/غير مربوط/.test(t)?'هذا المدرس غير مربوط بمادة هذا الدرس — اربطه بالمادة من تبويب المدرسون':/lesson_ids/.test(t)?'عمود lesson_ids ناقص في قاعدة البيانات — شغّل setup_v15.sql من Supabase → SQL Editor':/42703|PGRST204|slug|name_en|subject_ids/.test(code+' '+(j.message||''))?'عمود ناقص في قاعدة البيانات — شغّل setup_v13.sql من Supabase → SQL Editor ('+(j.message||code)+')':(r.status==401||r.status==403||code=='42501')?'ما عندكش صلاحية الحفظ — سجّل خروج وادخل بحساب الأدمن، أو شغّل setup_v13.sql':SQLERR+(j.message?' ['+j.message+']':''))};
const subChecks=(p,sel)=>`<div class="optb"><div class="optb-h">${ic('book',16)} المواد اللي بيدرّسها <em>مطلوب</em></div><div class="chk-g">${subs.map(s=>`<label class="chk"><input type="checkbox" class="${p}" value="${s.id}" ${(sel||[]).includes(s.id)?'checked':''}><span style="--c:${esc(s.color||'#0878C9')}">${esc(s.name)}</span></label>`).join('')||'<small class="muted">أضف مواد أولًا</small>'}</div></div>`,chk=p=>[...document.querySelectorAll('.'+p+':checked')].map(x=>+x.value),
lids=(p,sp)=>{const sb=chk(sp);return chk(p).filter(i=>sb.includes((ls.find(l=>l.id==i)||{}).subject_id))},
lsChecks=(p,sel)=>`<details class="optb" ${(sel||[]).length?'open':''}><summary class="optb-h">${ic('lock',16)} حصر المدرس في دروس معيّنة <em>اختياري — للأدمن فقط</em></summary><small class="muted">سيب كل الدروس بدون اختيار = المدرس يظهر في اختيار المدرس لكل دروس مواده. اختار درسًا أو أكتر = يظهر عند إضافة محتوى في الدروس دي بس (وده مش ظاهر لحد غيرك).</small>${subs.map(s=>{const L=ls.filter(l=>l.subject_id==s.id);return L.length?`<div class="lsg"><b>${esc(s.name)}</b><div class="chk-g">${L.map(l=>`<label class="chk"><input type="checkbox" class="${p}" value="${l.id}" ${(sel||[]).includes(l.id)?'checked':''}><span style="--c:${esc(s.color||'#0878C9')}">${esc(l.title)}</span></label>`).join('')}</div></div>`:''}).join('')}</details>`;
const CANNED=['شكرًا لتواصلك معنا، جاري مراجعة مشكلتك وهنرد عليك في أقرب وقت.','جرّب تحدّث الصفحة وتسجّل خروج ثم دخول مرة تانية، وبلغنا لو المشكلة استمرت.','ممكن تبعتلنا لقطة شاشة أو توضّح الخطوات اللي عملتها قبل ما تظهر المشكلة؟','تم حل المشكلة. لو واجهتك أي حاجة تانية افتح تذكرة جديدة.'];
const J=async(p,d=[])=>{const r=await post('rpc/'+p,{});return r.ok?r.json():d};
const modal=(t,h,ok)=>new Promise(res=>{document.body.insertAdjacentHTML('beforeend',`<div class="mdl" id="md"><div class="mb"><h3>${t}</h3><div class="form">${h}</div><div class="acts" style="margin-top:14px"><button class="bt p" id="mok">حفظ</button><button class="bt" id="mcx">إلغاء</button></div></div></div>`);const c=()=>$('#md').remove();$('#mcx').onclick=()=>{c();res(null)};$('#mok').onclick=async()=>{const b=$('#mok');b.disabled=true;if(await ok()===false){b.disabled=false;return}c();res(true)}});
const ICL={book:'كتاب',globe:'كرة أرضية',math:'رياضيات',flask:'علوم',map:'خريطة'},TS={open:'قيد المراجعة',answered:'تم الرد',closed:'مغلقة'},TC={general:'استفسار عام',tech:'مشكلة تقنية',account:'الحساب',content:'المحتوى',idea:'اقتراح',legacy:'رسالة قديمة'};
let tkA=[],qsA=[],rvA=[],ntA=[],TKS=0,TKM=[],TKF='all';
/* كل صفحة بتحمّل بياناتها هي بس (وبعدها بتتخزن في كاش الجهاز) — مفيش حاجة بتتحمّل إلا لما تفتح صفحتها */
const LK=(p,ttl)=>cget(p,ttl==null?SC:ttl,1),
 cnt=async p=>{try{const r=await rest(p+(p.includes('?')?'&':'?')+'select=id&limit=1',{headers:{Prefer:'count=exact'}});if(!r.ok)return null;const m=/\/(\d+)$/.exec(r.headers.get('content-range')||'');return m?+m[1]:null}catch(_){return null}},
 stfL=()=>post('rpc/edu_staff_list',{}).then(r=>r.ok?r.json():[]).catch(()=>[]),
 crsT=async ids=>{ids=[...new Set(ids)].filter(Boolean);return ids.length?get('aa_edu_courses?select=id,title,teacher_id&id=in.('+ids.join(',')+')').catch(()=>[]):[]};
/* محتوى درس واحد (كورسات + ملفات + فيديوهات حل + اختبارات) — بيتحمّل لما تضغط «المحتوى» على الدرس */
async function loadLesson(lid){
 let a=await LK('aa_edu_courses_v?lesson_id=eq.'+lid+'&order=id');if(R!='admin')a=a.filter(c=>c.teacher_id==TID);
 const so=await LK('aa_edu_courses?select=id,sort&lesson_id=eq.'+lid+'&order=id').catch(()=>[]),sm=Object.fromEntries(so.map(x=>[x.id,x.sort||0]));a.forEach(c=>c.sort=sm[c.id]||0);
 cs=cs.filter(c=>c.lesson_id!=lid);const keep=new Set(cs.map(c=>c.id));sols=sols.filter(x=>keep.has(x.course_id));fls=fls.filter(x=>keep.has(x.course_id));qzs=qzs.filter(x=>keep.has(x.course_id));
 cs=cs.concat(a);if(!a.length)return;const q='course_id=in.('+a.map(c=>c.id).join(',')+')';
 const [s,f,z]=await Promise.all([LK('aa_edu_course_solutions?'+q+'&order=id').catch(()=>[]),LK('aa_edu_course_files?'+q+'&order=id').catch(()=>[]),LK('aa_edu_quizzes?select=id,title,course_id,aa_edu_quiz_questions(count)&'+q+'&order=id').catch(()=>[])]);
 sols=sols.concat(s);fls=fls.concat(f);qzs=qzs.concat(z)}
async function loadTab(){const t=tab;
 if(t=='o'){const r0=await post('rpc/edu_admin_counts',{}).then(x=>x.ok?x.json():null).catch(()=>null);if(r0){OV=r0;return}
  /* لو setup_v16.sql لسه ما اتشغلش: الأعداد من الجداول مباشرة، وعدد المستخدمين مش بيتعرض عشان ميطلعش رقم غلط */
  const A=['aa_edu_profiles','aa_edu_courses','aa_edu_lessons','aa_edu_teachers','aa_edu_tickets?status=eq.open','aa_edu_questions?answer=is.null','aa_edu_applications?status=eq.pending'],v=await Promise.all(A.map(cnt));OV={users:null,courses:v[1],lessons:v[2],teachers:v[3],tickets:v[4],questions:v[5],apps:v[6]};return}
 if(t=='c'){const a=await Promise.all([LK('aa_edu_subjects?order=sort'),LK('aa_edu_lessons?order=subject_id,sort,id'),LK('aa_edu_teachers?order=id'),LK('aa_edu_courses?select=id,lesson_id,teacher_id&order=id')]);[subs,ls,ts]=a;cc=R=='admin'?a[3]:a[3].filter(c=>c.teacher_id==TID);CCN={};cc.forEach(c=>CCN[c.lesson_id]=(CCN[c.lesson_id]||0)+1);if(OL)await loadLesson(OL);return}
 if(t=='g'){[subs,ls]=await Promise.all([LK('aa_edu_subjects?order=sort'),LK('aa_edu_lessons?select=id,subject_id&order=id')]);return}
 if(t=='t'){[subs,ts,ls,stf]=await Promise.all([LK('aa_edu_subjects?order=sort'),LK('aa_edu_teachers?order=id'),LK('aa_edu_lessons?select=id,subject_id,title,sort&order=subject_id,sort,id'),stfL()]);return}
 if(t=='ap'){apA=await get('aa_edu_applications?order=created_at.desc&limit=300').catch(()=>[]);return}
 if(t=='x'){[us,stf]=await Promise.all([J('edu_admin_users'),stfL()]);usFull=true;return}
 if(t=='s'){tkA=await J('edu_admin_tickets');TRT=Object.fromEntries((await get('aa_edu_tickets?select=id,rating,rating_note&rating=not.is.null').catch(()=>[])).map(x=>[x.id,x]));if(TKS)TKM=await get('aa_edu_ticket_messages?ticket_id=eq.'+TKS+'&order=created_at').catch(()=>[]);return}
 if(t=='n'){ntA=await get('aa_edu_notifications?order=created_at.desc&limit=60').catch(()=>[]);if(!usFull){const ids=[...new Set(ntA.map(n=>n.user_id).filter(Boolean))];if(ids.length)us=await get('aa_edu_profiles?select=id,name,phone&id=in.('+ids.join(',')+')').catch(()=>[])}return}
 if(t=='qa'){qsA=await get('aa_edu_questions?order=created_at.desc&limit=300').catch(()=>[]);cs=await crsT(qsA.map(x=>x.course_id));if(R!='admin')cs=cs.filter(c=>c.teacher_id==TID);qsA=qsA.filter(x=>cs.some(c=>c.id==x.course_id));return}
 if(t=='rv'){rvA=await get('aa_edu_reviews?order=created_at.desc&limit=200').catch(()=>[]);cs=await crsT(rvA.map(x=>x.course_id));return}
 if(t=='a'){ads=await LK('aa_edu_ads?order=sort,id').catch(()=>[]);return}
 if(t=='b'){bks=await LK('aa_edu_books?order=id.desc').catch(()=>[]);return}
 if(t=='u'){ups=await LK('aa_edu_updates?order=created_at.desc').catch(()=>[]);return}
 if(t=='ab'){const r=await rest('aa_edu_about?id=eq.1').catch(()=>({ok:false}));ABerr=!r.ok;AB=r.ok?((await r.json())[0]||{}):{}}}
const kc=(i,n,l)=>`<div class="kc"><span class="ki">${ic(i,22)}</span><span><b>${n}</b><small>${l}</small></span></div>`;
const ib=(a,id,i,t,x='')=>`<button class="ib ${x}" data-a="${a}" data-id="${id}" title="${t}" aria-label="${t}">${ic(i,16)}</button>`;
const cname=id=>esc(cs.find(c=>c.id==id)?.title||'كورس');
const V={
o:()=>{const f=v=>v==null?'—':v,k=(i,n,l,t)=>`<a class="kc" href="${TURL[t]}"><span class="ki">${ic(i,22)}</span><span><b>${f(n)}</b><small>${l}</small></span></a>`;
 return `<div class="kp">${k('users',OV.users,'مستخدم','x')}${k('layers',OV.courses,'كورس','c')}${k('book',OV.lessons,'درس','c')}${k('cap',OV.teachers,'مدرس','t')}${k('ticket',OV.tickets,'تذكرة مفتوحة','s')}${k('msg',OV.questions,'سؤال بلا رد','qa')}${k('cap',OV.apps,'تقديم جديد','ap')}</div>
 <div class="card"><div class="ch"><b>إجراءات سريعة</b></div><div class="cbd acts"><button class="bt p" data-t="n">${ic('bell',16)} إرسال إشعار</button><button class="bt" data-t="c">${ic('plus',16)} رفع درس أو فيديو</button><button class="bt" data-t="u">${ic('mega',16)} نشر تحديث</button><button class="bt" data-t="g">${ic('book',16)} إدارة المواد</button><button class="bt" data-t="s">${ic('ticket',16)} صندوق الدعم</button></div></div>`},
g:()=>`<div class="card"><div class="ch"><b>المواد الدراسية</b><button class="bt p" data-a="sjf" data-id="">${ic('plus',16)} إضافة مادة</button></div>${subs.map(s=>`<div class="tr"><span class="t"><span class="ki" style="width:38px;height:38px;border-radius:10px;display:grid;place-items:center;color:#fff;background:${esc(s.color||'#0878C9')}">${ico(s.icon,20)}</span><span><b>${esc(s.name)}</b><br><small>${ls.filter(l=>l.subject_id==s.id).length} درس • <span dir="ltr">course-${esc(s.slug||'')}</span></small></span></span><span class="acts">${mv('movs',s.id)}${ib('sjf',s.id,'edit','تعديل')}${ib('sjd',s.id,'trash','حذف','dg')}</span></div>`).join('')||'<p class="empty">لا توجد مواد.</p>'}</div>`,
s:()=>{if(TKS){const t=tkA.find(x=>x.id==TKS);if(!t){TKS=0;return V.s()}
  return `<button class="bt" data-a="tkb">${ic('right',16)} كل التذاكر</button><div class="card" style="margin-top:12px"><div class="ch"><span><b>#${t.id} ${esc(t.subject)}</b><br><small class="muted">${esc(t.name||'—')} - <span dir="ltr">${esc(t.phone||'')}</span> - ${TC[t.category]||''}${TRT[t.id]?` - تقييم الطالب: ${stars(TRT[t.id].rating)}${TRT[t.id].rating_note?' «'+esc(TRT[t.id].rating_note)+'»':''}`:''}</small></span><span class="acts"><span class="bg ${t.status}">${TS[t.status]}</span>${t.status=='closed'?`<button class="bt" data-a="tkst" data-id="${t.id}" data-s="open">إعادة فتح</button>`:`<button class="bt" data-a="tkst" data-id="${t.id}" data-s="closed">${ic('check',16)} إغلاق</button>`}${ib('tkd',t.id,'trash','حذف التذكرة','dg')}</span></div>
  <div class="thr">${TKM.map(m=>`<div class="bub ${m.is_staff?'me':'st'}">${esc(m.body)}<small>${m.is_staff?'فريق الدعم':esc(t.name||'الطالب')} - ${ago(m.created_at)}</small></div>`).join('')||'<p class="empty">جارٍ التحميل...</p>'}</div>
  <div class="rp" style="flex-wrap:wrap"><select id="tkq" style="flex:1 1 100%"><option value="">إدراج رد جاهز...</option>${CANNED.map(x=>`<option value="${esc(x)}">${esc(x.slice(0,50))}...</option>`).join('')}</select><textarea id="tkt" maxlength="1500" placeholder="اكتب ردك على الطالب" style="flex:1"></textarea><button class="bt p" data-a="tkr">${ic('send',16)} إرسال الرد</button></div></div>`}
  const F=[['all','الكل'],['open','قيد المراجعة'],['answered','تم الرد'],['closed','مغلقة']],L=tkA.filter(t=>TKF=='all'||t.status==TKF);
  return `<div class="acts" style="margin-bottom:12px">${F.map(([k,t])=>`<button class="bt ${TKF==k?'p':''}" data-a="tkf" data-f="${k}">${t}${k!='all'?' ('+tkA.filter(x=>x.status==k).length+')':''}</button>`).join('')}</div><div class="card">${L.map(t=>`<div class="tr"><span class="t">${ic('msg',18)}<span><b>${esc(t.subject)}</b><br><small>${esc(t.name||'—')} - ${TC[t.category]||''} - ${t.msgs} رسالة - ${ago(t.updated_at)}</small></span></span><span class="acts"><span class="bg ${t.status}">${TS[t.status]}</span><button class="bt" data-a="tks" data-id="${t.id}">فتح والرد</button></span></div>`).join('')||'<p class="empty">لا توجد تذاكر.</p>'}</div>`},
n:()=>`<div class="card"><div class="ch"><b>إرسال إشعار للطلاب</b></div><div class="cbd form"><label>الجمهور</label><select id="nau"><option value="all">كل الطلاب</option><option value="one">مستخدم محدد</option></select><div id="nuw" hidden><label>اختر المستخدم</label><input id="nus" list="nul" placeholder="اكتب الاسم أو رقم الموبايل"><datalist id="nul">${us.map(u=>`<option value="${esc((u.name||'')+' - '+(u.phone||''))}">`).join('')}</datalist></div><label>العنوان</label><input id="nt1" maxlength="80" placeholder="عنوان الإشعار"><label>الرسالة</label><textarea id="nb1" rows="3" maxlength="400" placeholder="نص الرسالة"></textarea><label>رابط عند الضغط (اختياري)</label><input id="nl1" dir="ltr" placeholder="courses"><div><button class="bt p" data-a="nts">${ic('send',16)} إرسال الإشعار</button></div></div></div>
 <div class="card"><div class="ch"><b>الإشعارات المرسلة</b></div>${ntA.map(n=>{const u=n.user_id?us.find(x=>x.id==n.user_id):null;return `<div class="tr"><span class="t">${ic('bell',18)}<span><b>${esc(n.title)}</b> <span class="bg rl">${n.user_id?esc(u?u.name:'مستخدم'):'الجميع'}</span><br><small>${esc(n.body||'')} - ${ago(n.created_at)}</small></span></span>${ib('ntd',n.id,'trash','حذف','dg')}</div>`}).join('')||'<p class="empty">لم يتم إرسال إشعارات.</p>'}</div>`,
ab:()=>aboutView(),
qa:()=>`<div class="card">${qsA.slice().sort((a,b)=>!!a.answer-!!b.answer).map(q=>`<div class="tr" style="display:block"><div class="row"><span><b>${cname(q.course_id)}</b> <small class="muted">${ago(q.created_at)}</small></span>${ib('qd',q.id,'trash','حذف','dg')}</div><p style="margin:6px 0">${esc(q.body)}</p><div class="form"><textarea id="qa${q.id}" rows="2" placeholder="اكتب الرد">${esc(q.answer||'')}</textarea><div><button class="bt p" data-a="qs" data-id="${q.id}">${q.answer?'تحديث الرد':'إرسال الرد'}</button></div></div></div>`).join('')||'<p class="empty">لا توجد أسئلة.</p>'}</div>`,
rv:()=>`<div class="card">${rvA.map(r=>`<div class="tr"><span class="t">${stars(r.rating)}<span><b>${cname(r.course_id)}</b><br><small>${esc(r.comment||'بدون تعليق')} - ${ago(r.created_at)}</small></span></span>${ib('rvd',r.id,'trash','حذف','dg')}</div>`).join('')||'<p class="empty">لا توجد تقييمات.</p>'}</div>`
};

V.ap=()=>{const KS=['all',...Object.keys(APK)],SS=['pending','approved','rejected','withdrawn'],L=apA.filter(a=>(apS=='all'||a.status==apS)&&(apK=='all'||a.kind==apK)),fl=(a,k,l,n)=>`<button class="bt ${(a=='apS'?apS:apK)==k?'p':''}" data-a="apf" data-${a=='apS'?'s':'k'}="${k}">${l}${n!=null?' ('+n+')':''}</button>`;
 return `<div class="acts" style="margin-bottom:8px">${['all',...SS].map(k=>fl('apS',k,k=='all'?'كل الحالات':APS[k],k=='all'?apA.length:apA.filter(x=>x.status==k).length)).join('')}</div><div class="acts" style="margin-bottom:12px">${KS.map(k=>fl('apK',k,k=='all'?'كل الأنواع':APK[k])).join('')}</div>`+
 (L.map(a=>{const F=APF[a.kind]||[],d=a.data||{};return `<div class="card"><div class="ch"><span><b>${esc(a.full_name)}</b> <span class="bg rl">${APK[a.kind]||a.kind}</span><br><small class="muted"><span dir="ltr">${esc(a.phone||'—')}</span> - ${ago(a.created_at)} - موافقة على البنود ${esc(a.terms_version)}</small></span><span class="bg ${a.status=='pending'?'open':a.status=='approved'?'answered':'closed'}">${APS[a.status]||a.status}</span></div>
  <div class="cbd">${F.map(([k,l,t])=>d[k]?`<div style="margin-bottom:8px"><small class="muted">${l}</small><div>${t=='url'?`<a dir="ltr" class="lnk" target="_blank" rel="noopener noreferrer" href="${/^https?:\/\//i.test(d[k])?esc(d[k]):'#'}">${esc(d[k])}</a>`:esc(d[k])}</div></div>`:'').join('')||'<small class="muted">لا توجد تفاصيل.</small>'}
  <div class="form"><textarea id="apn${a.id}" rows="2" maxlength="300" placeholder="ملاحظة للطالب (مطلوبة عند الرفض، تظهر له في الإشعار)">${esc(a.admin_note||'')}</textarea><div class="acts">${a.status!='approved'?`<button class="bt p" data-a="apr" data-id="${a.id}" data-s="approved">${ic('check',16)} قبول</button>`:''}${a.status!='rejected'?`<button class="bt" data-a="apr" data-id="${a.id}" data-s="rejected">${ic('x',16)} رفض</button>`:''}${a.status!='pending'&&a.status!='withdrawn'?`<button class="bt" data-a="apr" data-id="${a.id}" data-s="pending">إعادة للمراجعة</button>`:''}${ib('apd',a.id,'trash','حذف','dg')}</div>${a.kind=='teacher'&&a.status=='approved'?'<small class="muted">لإضافته كمدرس: تبويب «المدرسون» ← أضفه واختر مادته.</small>':''}</div></div></div>`}).join('')||'<div class="card"><p class="empty">لا توجد تقديمات بهذا الفلتر. (لو لسه ما شغّلتش setup_v9.sql شغّله من Supabase)</p></div>')};
document.addEventListener('change',e=>{if(e.target.id=='cl'&&$('#ct')){const L=ls.find(l=>l.id==+e.target.value)||{},cur=+$('#ct').value;$('#ct').innerHTML=opt(tForL(L),t=>esc(t.name),cur)}if(e.target.id=='tkq'&&e.target.value&&$('#tkt')){$('#tkt').value=e.target.value;e.target.value=''}});
const bySort=(a,b)=>(a.sort||0)-(b.sort||0)||a.id-b.id,SQLERR='تعذر الحفظ — شغّل setup_v13.sql من Supabase وتأكد من صلاحيات حسابك.';
const UPERR='تعذر رفع الملف. تأكد من تشغيل setup_uploads.sql ومن حجم الملف (الحد الافتراضي 50MB).';
const flagU=(v,cb)=>v&&$(cb)&&$(cb).checked&&ytId(v)?cleanU(v)+'#noembed':v;
const sel=(id,a,f)=>`<select id="${id}">${a.map(f).join('')}</select>`,fv=id=>$('#'+id).value.trim(),say=t=>toast(t,/^(تعذر|اكتب|ارفع|غير|لا |حسابك|رقم|كلمة|السؤال|الحساب|اختر)/.test(t));
const fup=(id,acc,lab)=>`<div class="up"><small class="muted">${lab}</small><label class="fpick"><input type="file" id="${id}" accept="${acc}"><span class="fp-b">${ic('upload',16)} اختر ملف</span><span class="fp-n">لم يتم اختيار ملف</span></label><div class="pbar"><i id="${id}_p" style="width:0"></i></div></div>`;
const up=async(id,folder)=>{const f=$('#'+id)?.files[0];if(!f)return null;return upload(f,folder,v=>{const p=$('#'+id+'_p');if(p)p.style.width=v+'%'})};
const FA='.pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx,.zip,image/*',VA='video/*,.mp4,.webm,.mov';
const tChoices=c=>{const a=tForL(ls.find(l=>l.id==c.lesson_id)||{});return a.some(t=>t.id==c.teacher_id)?a:a.concat(ts.filter(t=>t.id==c.teacher_id))};
const opt=(a,f,v)=>a.map(x=>`<option value="${x.id}" ${x.id==v?'selected':''}>${f(x)}</option>`).join('');
const sel2=(id,a,f,v)=>`<select id="${id}">${opt(a,f,v)}</select>`;
const mv=(a,id)=>`<button class="btn btn-o btn-s" data-a="${a}" data-id="${id}" data-d="-1" title="أعلى">${ic('up',16)}</button><button class="btn btn-o btn-s" data-a="${a}" data-id="${id}" data-d="1" title="أسفل">${ic('down',16)}</button>`;
const lessonOpts=v=>ls.filter(l=>R=='admin'||(SV().some(s=>s.id==l.subject_id)&&okL(l))).map(l=>`<option value="${l.id}" ${l.id==v?'selected':''}>${esc(subs.find(s=>s.id==l.subject_id)?.name||'')} — ${esc(l.title)}</option>`).join('');
function panel(c){if(!P||P.id!=c.id)return'';
 if(P.k=='q')return `<div class="box fm sf" style="border-color:var(--bl)"><b>${P.qid?'تعديل الاختبار':'اختبار جديد'}</b><input id="qt" value="${esc(QT)}" placeholder="عنوان الاختبار" maxlength="120">${QI.map((x,i)=>`<div class="box"><div class="row"><b>سؤال ${i+1}</b>${QI.length>1?`<button class="btn btn-o btn-s" data-a="delq" data-i="${i}">حذف</button>`:''}</div><input id="q${i}" value="${esc(x.q)}" placeholder="نص السؤال">${x.o.map((o,j)=>`<label class="row" style="justify-content:flex-start;gap:8px"><input type="radio" name="c${i}" value="${j}" ${x.a==j?'checked':''} style="width:auto"><input id="o${i}_${j}" value="${esc(o)}" placeholder="الاختيار ${j+1}"></label>`).join('')}<small class="muted">اختر الدائرة بجانب الإجابة الصحيحة</small></div>`).join('')}<div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn btn-o btn-s" data-a="addq">${ic('plus',14)} سؤال</button><button class="btn btn-p btn-s" data-a="saveq">حفظ الاختبار</button><button class="btn btn-o btn-s" data-a="close">إلغاء</button></div></div>`;
 if(P.k=='e')return `<div class="box fm sf" style="border-color:var(--bl)"><b>تعديل الكورس</b><select id="cl">${lessonOpts(c.lesson_id)}</select>${R=='admin'?sel2('ct',tChoices(c),t=>esc(t.name),c.teacher_id):''}<input id="cn" value="${esc(c.title)}" placeholder="عنوان الكورس" maxlength="140"><textarea id="cd" rows="3" placeholder="وصف الكورس">${esc(c.description||'')}</textarea>${fup('cif','image/*','صورة الغلاف (ارفع صورة جديدة أو اترك الحالية)')}<input id="ci" dir="ltr" value="${esc(c.image||'')}" placeholder="رابط صورة"> ${fup('cvf',VA,'فيديو الشرح (ارفع فيديو mp4 — بدون أي علامة يوتيوب)')}<input id="cv" dir="ltr" value="${esc(cleanU(c.video_url||''))}" placeholder="رابط فيديو (يوتيوب / درايف / mp4)"><label class="ne"><input type="checkbox" id="cne" ${NE(c.video_url)?'checked':''} style="width:auto"> الفيديو ممنوع تضمينه (يظهر للطالب كارت «شاهده على يوتيوب»)</label><label><input type="checkbox" id="cf" ${c.is_free?'checked':''} style="width:auto"> مجاني</label>${R=='admin'?`<label><input type="checkbox" id="cfe" ${c.is_featured?'checked':''} style="width:auto"> كورس مختار (يظهر أولًا)</label>`:''}<div style="display:flex;gap:8px"><button class="btn btn-p btn-s" data-a="savec" data-id="${c.id}">حفظ التعديلات</button><button class="btn btn-o btn-s" data-a="close">إلغاء</button></div></div>`;
 const f=P.k!='s',m=P.k=='m';return `<div class="box fm sf" style="border-color:var(--bl)"><b>${m?'إضافة ملخص':f?'إضافة ملف / صورة':'إضافة فيديو حل'}</b><input id="pt" placeholder="العنوان" maxlength="140">${fup('pf',f?FA:VA,f?'ارفع ملف أو صورة':'ارفع فيديو')}<input id="pl" dir="ltr" placeholder="أو الصق رابط ${f?'':'(يوتيوب / درايف / mp4)'}">${f?'':'<label class="ne"><input type="checkbox" id="pne" style="width:auto"> الفيديو ممنوع تضمينه (كارت «شاهده على يوتيوب»)</label>'}<div style="display:flex;gap:8px"><button class="btn btn-p btn-s" data-a="savep">حفظ</button><button class="btn btn-o btn-s" data-a="close">إلغاء</button></div></div>`}
const edBox=(k,id,inner,save)=>P&&P.k==k&&P.id==id?`<div class="box fm sf" style="border-color:var(--bl)">${inner}<div style="display:flex;gap:8px"><button class="btn btn-p btn-s" data-a="${save}" data-id="${id}">حفظ</button><button class="btn btn-o btn-s" data-a="close">إلغاء</button></div></div>`:'';
const nph=v=>String(v||'').replace(/[٠-٩]/g,x=>'٠١٢٣٤٥٦٧٨٩'.indexOf(x)).replace(/^\+?20/,'0').replace(/\D/g,'');
/* كابتشا Turnstile لإنشاء حساب مدرس (بتشتغل بس لو TURNSTILE_SITEKEY متحط في config.js) */
function cfAsk(){return new Promise(res=>{const K=typeof TURNSTILE_SITEKEY==='string'?TURNSTILE_SITEKEY:'';if(!K)return res('');
 const o=document.createElement('div');o.style.cssText='position:fixed;inset:0;background:rgba(0,0,0,.45);display:grid;place-items:center;z-index:9999';
 o.innerHTML='<div style="background:#fff;padding:20px;border-radius:14px;text-align:center"><p style="margin:0 0 12px;font-weight:600">تحقق أمني قبل إنشاء الحساب</p><div id="cfa"></div><button type="button" class="btn btn-o btn-s" style="margin-top:12px">إلغاء</button></div>';document.body.appendChild(o);
 const done=t=>{o.remove();res(t)};o.querySelector('button').onclick=()=>done(null);
 const go=()=>turnstile.render('#cfa',{sitekey:K,language:'ar',callback:done});
 if(window.turnstile)go();else{window.cfReady2=go;const s=document.createElement('script');s.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit&onload=cfReady2';document.head.appendChild(s)}})}
async function mkAcc(phone,pw,name){const tok=await cfAsk();if(tok===null)return 'err';const h={apikey:SUPA_KEY,'Content-Type':'application/json'};let r,j;try{r=await fetch(SUPA_URL+'/auth/v1/signup',{method:'POST',headers:h,body:JSON.stringify({email:`u${phone}@academy-users.com`,password:pw,data:{name,phone},gotrue_meta_security:tok?{captcha_token:tok}:undefined})});j=await r.json().catch(()=>({}))}catch(_){return 'err'}
 if(!r.ok)return (j.error_code||j.code)=='user_already_exists'?'exists':'err';if(!j.access_token)return 'confirm';
 await fetch(SUPA_URL+'/rest/v1/aa_edu_profiles?on_conflict=id',{method:'POST',headers:{...h,Authorization:'Bearer '+j.access_token,Prefer:'resolution=ignore-duplicates,return=minimal'},body:JSON.stringify({id:j.user.id,name,phone,grade:'prep3'})}).catch(()=>{});return 'ok'}
const rb=(a,id,t)=>`<button class="btn btn-o btn-s" data-a="${a}" data-id="${id}">${t}</button>`;
const courseBox=c=>`<div class="box"><div class="row"><b>${c.is_featured?ic('star',14,'fill amber')+' ':''}${esc(c.title)}</b><span style="display:flex;gap:6px;flex-wrap:wrap"><a class="btn btn-o btn-s" href="course?id=${c.id}">عرض</a><button class="btn btn-o btn-s" data-a="op" data-k="e" data-id="${c.id}">تعديل</button>${mv('movc',c.id)}</span></div><small class="muted">${esc(c.teacher_name||'')}</small>`+
 sols.filter(x=>x.course_id==c.id).map(x=>`<div class="lg"><span>${ic('video',16)} ${esc(x.title)}</span><span style="display:flex;gap:6px">${rb('rns',x.id,'تعديل')}${rb('dels',x.id,'حذف')}</span></div>`).join('')+
 fls.filter(x=>x.course_id==c.id).map(x=>`<div class="lg"><span>${x.kind=='summary'?ic('note',16)+' ملخص:':ic('file',16)} ${esc(x.title)}</span><span style="display:flex;gap:6px">${rb('rnf',x.id,'تعديل')}${rb('delf',x.id,'حذف')}</span></div>`).join('')+
 qzs.filter(q=>q.course_id==c.id).map(q=>`<div class="lg"><span>${ic('quiz',16)} ${esc(q.title)} <small class="muted">${q.aa_edu_quiz_questions?.[0]?.count??''} سؤال</small></span><span style="display:flex;gap:6px">${rb('eq',q.id,'تعديل')}${rb('delz',q.id,'حذف')}</span></div>`).join('')+
 `<div style="margin:8px 0;display:flex;gap:8px;flex-wrap:wrap"><button class="btn btn-o btn-s" data-a="op" data-k="f" data-id="${c.id}">${ic('plus',14)} ملف/صورة</button><button class="btn btn-o btn-s" data-a="op" data-k="m" data-id="${c.id}">${ic('plus',14)} ملخص</button><button class="btn btn-o btn-s" data-a="op" data-k="s" data-id="${c.id}">${ic('plus',14)} فيديو حل</button><button class="btn btn-o btn-s" data-a="op" data-k="q" data-id="${c.id}">${ic('plus',14)} اختبار</button>${rb('delc',c.id,'حذف')}</div>${panel(c)}</div>`;
const addCourse=l=>`<div class="box fm sf"><b>إضافة فيديو / كورس داخل «${esc(l.title)}»</b>${R=='admin'?(tForL(l).length?sel('nct',tForL(l),t=>`<option value="${t.id}">${esc(t.name)}</option>`):'<div class="optb"><small class="msg">لا يوجد مدرس متاح لهذا الدرس — اربط مدرسًا بمادته (أو بهذا الدرس تحديدًا) من صفحة «المدرسون» أولًا.</small></div>'):''}<input id="ncn" placeholder="عنوان الفيديو / الكورس" maxlength="140"><textarea id="ncd" placeholder="وصف (اختياري)" rows="2"></textarea>${fup('ncif','image/*','صورة الغلاف (اختياري)')}<input id="nci" dir="ltr" placeholder="أو رابط صورة">${fup('ncvf',VA,'فيديو الشرح (ارفع mp4 للأفضل)')}<input id="ncv" dir="ltr" placeholder="أو رابط فيديو (يوتيوب / درايف / mp4)"><label class="ne"><input type="checkbox" id="ncne" style="width:auto"> الفيديو ممنوع تضمينه (يظهر للطالب كارت «شاهده على يوتيوب» بدل المشغّل)</label><label><input type="checkbox" id="ncf" checked style="width:auto"> مجاني</label><button class="btn btn-p btn-s" data-a="addc" data-id="${l.id}">إضافة</button></div>`;
const lk=id=>stf.find(x=>x.teacher_id==id&&x.role=='teacher');

let AB={},ABerr=false;
const aboutView=()=>`<div class="box fm sf"><b>${ic('info',18)} عن المنصة</b>${ABerr?'<div class="optb"><small class="msg">جدول aa_edu_about مش موجود لسه — شغّل ملف setup_about.sql من Supabase (SQL Editor) مرة واحدة وحدّث الصفحة.</small></div>':''}<input id="abpt" placeholder="عنوان تعريف المنصة" maxlength="80" value="${esc(AB.platform_title||'')}"><textarea id="abpx" rows="4" placeholder="كلام عن المنصة ورسالتها">${esc(AB.platform_text||'')}</textarea></div><div class="box fm sf"><b>${ic('user',18)} عنّي (صاحب المنصة)</b><input id="abn" placeholder="اسمك" maxlength="80" value="${esc(AB.name||'')}"><input id="abr" placeholder="وصفك (مثال: مؤسس المنصة ومدرس رياضيات)" maxlength="120" value="${esc(AB.role_title||'')}"><textarea id="abb" rows="5" placeholder="نبذة عنك">${esc(AB.bio||'')}</textarea><div class="trow" style="padding:0">${AB.photo?`<span class="u-av" style="width:64px;height:64px;background-image:url('${esc(AB.photo)}')"></span>`:''}<div style="flex:1;min-width:0">${fup('abpf','image/*','صورتك (بتتحوّل WebP وتتضغط تلقائيًا)')}</div></div><input id="abp" dir="ltr" placeholder="أو رابط صورة" value="${esc(AB.photo||'')}"><textarea id="abe" rows="5" placeholder="خبراتك — كل خبرة في سطر">${esc(AB.experience||'')}</textarea><input id="abu" dir="ltr" placeholder="رابط صفحتك (فيسبوك / يوتيوب / موقع) — لازم يبدأ بـ https://" value="${esc(AB.page_url||'')}"><input id="abl" placeholder="اسم زر الصفحة (مثال: صفحتي على فيسبوك)" maxlength="60" value="${esc(AB.page_label||'')}"><textarea id="abs" rows="3" dir="ltr" placeholder="روابط إضافية — كل رابط في سطر بالشكل: الاسم|الرابط">${esc(AB.socials||'')}</textarea><button class="btn btn-p btn-s" data-a="saveab">حفظ</button><small class="muted">قسم «الدعم المادي للمنصة» ظاهر للطلاب بعلامة «قريبًا» لحد ما تضيف تفاصيله.</small></div>`;
function draw(){const T=(R=='admin'?[['o','نظرة عامة','chart'],['c','المحتوى','layers'],['g','المواد','book'],['t','المدرسون','cap'],['ap','التقديمات','user'],['x','المستخدمون','users'],['s','الدعم','ticket'],['n','الإشعارات','bell'],['qa','أسئلة الطلاب','msg'],['rv','التقييمات','star'],['a','الإعلانات','image'],['b','الكتب','book'],['u','التحديثات','mega'],['ab','عن المنصة','info']]:[['c','المحتوى','layers'],['qa','أسئلة الطلاب','msg']]);let b='';const BT=tab;if(BOOT)tab='_';
 if(tab=='c')b=(SV().length?'':'<p class="empty">لم يتم ربط حسابك بأي مادة بعد — اطلب من الأدمن ربطك بمادتك من تبويب المدرسون.</p>')+SV().map(s=>{const L=ls.filter(l=>l.subject_id==s.id&&okL(l));return `<h3 class="lsn">${esc(s.name)} <small>${L.length} درس</small></h3>`+(R=='admin'?`<div class="box row"><input id="ln${s.id}" placeholder="عنوان درس جديد في ${esc(s.name)}" maxlength="120" style="flex:1;min-width:160px"><input id="lu${s.id}" placeholder="الوحدة (اختياري)" maxlength="120" style="flex:1;min-width:160px"><input id="lsl${s.id}" dir="ltr" placeholder="slug إنجليزي للرابط (اختياري)" maxlength="60" style="flex:1;min-width:140px"><button class="btn btn-p btn-s" data-a="addl" data-id="${s.id}">${ic('plus',14)} إضافة درس</button></div>`:'')+(L.map(l=>{const m=cs.filter(c=>c.lesson_id==l.id).sort(bySort),o=OL==l.id;return `<div class="box"><div class="row"><span><b>${esc(l.title)}</b> <small class="muted">${CCN[l.id]||0} محتوى</small></span><span style="display:flex;gap:6px;flex-wrap:wrap"><button class="btn btn-p btn-s" data-a="tgl" data-id="${l.id}">${o?'إخفاء':'المحتوى'}</button>${R=='admin'?mv('movl',l.id)+rb('rnl',l.id,'تعديل')+rb('dell',l.id,'حذف'):''}</span></div>${o?`<div style="margin-top:10px">${addCourse(l)}${LD==l.id?'<p class="empty">جارٍ تحميل المحتوى...</p>':m.map(courseBox).join('')||'<p class="muted">لا يوجد محتوى في هذا الدرس بعد.</p>'}</div>`:''}</div>`}).join('')||'<p class="muted">لا توجد دروس.</p>')}).join('');
 if(tab=='t')b=`<div class="box fm sf"><b>إضافة مدرس جديد</b><input id="ntn" placeholder="اسم المدرس (مطلوب)" maxlength="60"><input id="ntne" dir="ltr" placeholder="الاسم بالإنجليزي للرابط — مثال: Amr Sami (اختياري)" maxlength="60"><input id="ntsl" dir="ltr" placeholder="slug مخصص (اختياري — لو سبته فاضي يتولّد من الاسم أو عشوائي)" maxlength="60">${subChecks('nsc',[])}${lsChecks('nlc',[])}<input id="ntb" placeholder="نبذة قصيرة (اختياري)">${fup('ntif','image/*','صورة المدرس — اختياري (بتتحوّل WebP وتتضغط تلقائيًا)')}<input id="nti" dir="ltr" placeholder="أو رابط صورة (اختياري)"><div class="optb"><div class="optb-h">${ic('lock',16)} حساب دخول المدرس <em>اختياري</em></div><small class="muted">تقدر تضيف المدرس بدون موبايل أو حساب، وتربط له حساب في أي وقت من زر «ربط حساب».</small><input id="ntp" dir="ltr" inputmode="numeric" placeholder="رقم موبايل المدرس (اختياري)" maxlength="14"><input id="ntw" dir="ltr" autocomplete="off" placeholder="كلمة سر المدرس (اختياري — 6 أحرف على الأقل)" maxlength="64"><small class="muted">لو الرقم مسجّل قبل كده سيب كلمة السر فاضية وهيتم ربطه بحسابه.</small></div><button class="btn btn-p btn-s" data-a="addt">إضافة المدرس</button></div>`+ts.map(t=>{const k=lk(t.id);return `<div class="box trow-w"><div class="trow"><span class="u-av" ${t.image?`style="background-image:url('${esc(t.image)}')"`:''}>${t.image?'':esc((t.name||'؟').replace(/^أ\.\s*/,'').charAt(0))}</span><span class="u-i"><span class="u-n"><b>${esc(t.name)}</b>${k?'<span class="bg rl">حساب مربوط</span>':'<span class="bg closed">بدون حساب</span>'}</span><span class="u-m">${tsub(t).map(i=>`<span class="bg rl">${esc((subs.find(s=>s.id==i)||{}).name||'')}</span>`).join('')||'<span class="bg closed">بدون مادة</span>'}${tlid(t).length?`<span class="bg open">${tlid(t).length==1?'درس: '+esc((ls.find(l=>l.id==tlid(t)[0])||{}).title||''):tlid(t).length+' دروس محددة'}</span>`:''}<span dir="ltr" class="muted">?t=${esc(t.slug||'')}</span>${t.bio?`<span>${esc(t.bio)}</span>`:''}${k?`<span dir="ltr">${esc(k.phone||String(k.email).slice(1).split('@')[0])}</span>`:''}</span></span><span class="acts">${rb('lnk',t.id,k?'تغيير الحساب':'ربط حساب')}<button class="btn btn-o btn-s" data-a="op" data-k="et" data-id="${t.id}">تعديل</button>${rb('delt',t.id,'حذف')}</span></div>${edBox('et',t.id,`<b>تعديل المدرس</b><input id="tn" value="${esc(t.name)}" maxlength="60"><input id="tne" dir="ltr" value="${esc(t.name_en||'')}" placeholder="الاسم بالإنجليزي" maxlength="60"><input id="tsl" dir="ltr" value="${esc(t.slug||'')}" placeholder="slug الرابط" maxlength="60">${subChecks('tsc',tsub(t))}${lsChecks('tlc',tlid(t))}<input id="tb" value="${esc(t.bio||'')}" placeholder="نبذة (اختياري)">${fup('tif','image/*','صورة جديدة (اختياري)')}<input id="ti" dir="ltr" value="${esc(t.image||'')}" placeholder="رابط صورة (اختياري)">`,'savet')}</div>`}).join('');
 if(tab=='x')b=`<div class="srch">${ic('search',18)}<input id="us" type="search" placeholder="ابحث بالاسم أو رقم الموبايل..." dir="auto" autocomplete="off"></div><div class="cntline"><span><b>${us.length}</b> مستخدم</span><span><b>${us.filter(x=>x.banned).length}</b> محظور</span></div><div id="ul">`+us.map(x=>{const k=stf.find(y=>y.user_id==x.id);return `<div class="box urow" data-q="${esc((x.name||'')+' '+(x.phone||''))}"><span class="u-av ${x.banned?'ban':''}">${esc((x.name||'؟').trim().charAt(0))}</span><span class="u-i"><span class="u-n"><b>${esc(x.name||'—')}</b>${k?`<span class="bg rl ${k.role=='admin'?'adm-r':''}">${k.role=='admin'?'أدمن':'مدرس'}</span>`:''}${x.banned?'<span class="bg closed">محظور</span>':''}</span><span class="u-m"><span dir="ltr">${esc(x.phone||'—')}</span><span class="u-pt">${x.points||0} نقطة</span></span>${x.banned&&x.ban_reason?`<small class="msg">${esc(x.ban_reason)}</small>`:''}</span><span class="acts">${ib('uf',x.id,'edit','تعديل')}<button class="btn ${x.banned?'btn-p':'btn-o'} btn-s" data-a="ban" data-id="${x.id}" data-b="${x.banned?0:1}">${x.banned?'فك الحظر':'حظر'}</button></span></div>`}).join('')+'</div>';
  if(tab=='a')b=`<div class="box fm sf"><b>إضافة إعلان (يظهر في لافتة الرئيسية)</b><input id="at1" placeholder="عنوان الإعلان / اسم المتجر">${fup('aif','image/*','ارفع صورة عريضة (الأفضل 1600×900 — بتظهر كاملة بدون قص)')}<input id="ai" dir="ltr" placeholder="أو رابط صورة"><input id="al" dir="ltr" placeholder="رابط عند الضغط (اختياري)"><button class="btn btn-p btn-s" data-a="adda">إضافة</button></div>`+ads.map(a=>`<div class="box"><div class="row"><span><i class="dot ${a.active?'on':''}"></i>${esc(a.title||'')}</span><span style="display:flex;gap:6px;flex-wrap:wrap">${mv('mova',a.id)}<button class="btn btn-o btn-s" data-a="tga" data-id="${a.id}">${a.active?'إخفاء':'إظهار'}</button><button class="btn btn-o btn-s" data-a="op" data-k="ea" data-id="${a.id}">تعديل</button><button class="btn btn-o btn-s" data-a="dela" data-id="${a.id}">حذف</button></span></div>${edBox('ea',a.id,`<b>تعديل الإعلان</b><input id="at1" value="${esc(a.title||'')}">${fup('aif','image/*','صورة جديدة (عريضة)')}<input id="ai" dir="ltr" value="${esc(a.image||'')}"><input id="al" dir="ltr" value="${esc(a.link||'')}" placeholder="رابط عند الضغط">`,'savea')}</div>`).join('');
 if(tab=='b')b=`<div class="box fm sf"><b>إضافة كتاب</b><input id="bt" placeholder="عنوان الكتاب" maxlength="140"><input id="bs" placeholder="المادة (نص)">${fup('bff','.pdf,.doc,.docx,.zip','ارفع ملف الكتاب')}<input id="bu" dir="ltr" placeholder="أو رابط الكتاب">${fup('bcf','image/*','غلاف الكتاب')}<input id="bc" dir="ltr" placeholder="أو رابط الغلاف"><button class="btn btn-p btn-s" data-a="addb">إضافة</button></div>`+bks.map(x=>`<div class="box"><div class="row"><span>${ic('book',16)} ${esc(x.title)} <small class="muted">${esc(x.subject||'')}</small></span><span style="display:flex;gap:6px"><button class="btn btn-o btn-s" data-a="op" data-k="eb" data-id="${x.id}">تعديل</button><button class="btn btn-o btn-s" data-a="delb" data-id="${x.id}">حذف</button></span></div>${edBox('eb',x.id,`<b>تعديل الكتاب</b><input id="bt" value="${esc(x.title)}"><input id="bs" value="${esc(x.subject||'')}" placeholder="المادة">${fup('bff','.pdf,.doc,.docx,.zip','ملف جديد')}<input id="bu" dir="ltr" value="${esc(x.url||'')}">${fup('bcf','image/*','غلاف جديد')}<input id="bc" dir="ltr" value="${esc(x.cover||'')}">`,'saveb')}</div>`).join('');
 if(tab=='u')b=`<div class="box fm sf"><b>إضافة تحديث / إعلان للطلاب</b><input id="ut" placeholder="العنوان" maxlength="140"><textarea id="ub" rows="3" placeholder="التفاصيل"></textarea><button class="btn btn-p btn-s" data-a="addu">إضافة</button></div>`+ups.map(x=>`<div class="box"><div class="row"><span>${ic('mega',16)} <b>${esc(x.title)}</b></span><span style="display:flex;gap:6px"><button class="btn btn-o btn-s" data-a="op" data-k="eu" data-id="${x.id}">تعديل</button><button class="btn btn-o btn-s" data-a="delu" data-id="${x.id}">حذف</button></span></div><div class="muted">${esc(x.body||'')}</div>${edBox('eu',x.id,`<b>تعديل التحديث</b><input id="ut" value="${esc(x.title)}"><textarea id="ub" rows="3">${esc(x.body||'')}</textarea>`,'saveu')}</div>`).join('');
 if(V[tab])b=V[tab]();
 tab=BT;if(BOOT)b='<p class="empty">جارٍ التحميل...</p>';
 $('#o').innerHTML=`<div class="ktabs">${T.map(([k,t,i])=>`<a class="${k==tab?'on':''}" href="${TURL[k]}">${ic(i,16)}${t}${k=='s'&&tkA.some(x=>x.status=='open')?`<span class="cnt">${tkA.filter(x=>x.status=='open').length}</span>`:''}${k=='qa'&&qsA.some(x=>!x.answer)?`<span class="cnt">${qsA.filter(x=>!x.answer).length}</span>`:''}${k=='ap'&&apA.some(x=>x.status=='pending')?`<span class="cnt">${apA.filter(x=>x.status=='pending').length}</span>`:''}</a>`).join('')}</div>${b}`}
const run=async(r,m)=>{if(!r.ok){await fail(r);return null}P=null;await loadTab();draw();say(m||'تم');return r};
async function move(list,id,d,table){const i=list.findIndex(x=>x.id==id),j=i+d;if(i<0||j<0||j>=list.length)return;const a=list.slice();[a[i],a[j]]=[a[j],a[i]];
 const rs=await Promise.all(a.map((x,k)=>x.sort==k+1?null:rest(table+'?id=eq.'+x.id,{method:'PATCH',body:JSON.stringify({sort:k+1})})));
 if(rs.some(r=>r&&!r.ok))return say(SQLERR);await loadTab();draw();say('تم الترتيب')}
function collect(){const t=$('#qt');if(t)QT=t.value;QI=QI.map((x,i)=>{const r=document.querySelector(`input[name=c${i}]:checked`);return{q:$('#q'+i)?.value||'',o:x.o.map((_,j)=>$(`#o${i}_${j}`)?.value||''),a:r?+r.value:x.a}})}
const blank=()=>({q:'',o:['','','',''],a:0});

document.addEventListener('change',e=>{const i=e.target;if(!i||i.type!='file')return;const w=i.closest('.fpick');if(!w)return;const f=i.files[0],n=w.querySelector('.fp-n');w.querySelectorAll('.fp-th,.fp-w').forEach(x=>x.remove());
 if(!f){w.classList.remove('has');n.textContent='لم يتم اختيار ملف';return}
 w.classList.add('has');n.textContent=f.name+' • '+(f.size>1048576?(f.size/1048576).toFixed(1)+' MB':Math.max(1,Math.round(f.size/1024))+' KB');
 if(/^image\/(jpe?g|png|bmp|webp)$/.test(f.type)){const t=document.createElement('span');t.className='fp-th';t.style.backgroundImage="url('"+URL.createObjectURL(f)+"')";w.insertBefore(t,w.querySelector('.fp-b'));const k=document.createElement('span');k.className='fp-w';k.textContent='WebP';w.appendChild(k)}});
document.addEventListener('input',e=>{if(e.target.id!='us')return;const q=e.target.value.trim().toLowerCase();document.querySelectorAll('#ul [data-q]').forEach(x=>x.style.display=x.dataset.q.toLowerCase().includes(q)?'':'none')});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||!R)return;const a=b.dataset.a,id=b.dataset.id;
 if(b.dataset.t){location.href=TURL[b.dataset.t];return}
 if(a=='close'){P=null;return draw()}
 if(a=='tgl'){if(OL==id){OL=0;P=null;return draw()}OL=+id;LD=OL;P=null;draw();try{await loadLesson(OL)}catch(_){say('تعذر تحميل المحتوى')}LD=0;return draw()}
 if(a=='addl'){const sid=+id,t=fv('ln'+sid);if(t.length<2)return say('اكتب عنوان الدرس.');return run(await post('aa_edu_lessons',{subject_id:sid,title:t,unit:fv('lu'+sid)||null,slug:slg(fv('lsl'+sid)),sort:ls.filter(l=>l.subject_id==sid).length+1}),'تمت إضافة الدرس')}
 if(a=='addc'){const t=R=='admin'?+fv('nct'):TID;if(!t)return say('حسابك غير مربوط بمدرس.');if(fv('ncn').length<2)return say('اكتب عنوان الكورس.');
  b.disabled=true;say('جارٍ الرفع... لا تغلق الصفحة');let img,vid;try{img=await up('ncif','covers')||fv('nci')||null;vid=await up('ncvf','videos')||fv('ncv')||null}catch(_){b.disabled=false;return say(UPERR)}vid=flagU(vid,'#ncne')||null;
  return run(await post('aa_edu_courses',{lesson_id:+id,teacher_id:t,title:fv('ncn'),description:fv('ncd')||null,image:img,video_url:vid,is_free:$('#ncf').checked}),'تمت الإضافة — أضف له الملفات والملخصات والاختبارات')}
 if(a=='addt'){const n=fv('ntn'),ph=nph(fv('ntp')),pw=$('#ntw').value;if(n.length<2)return say('اكتب اسم المدرس.');if(!chk('nsc').length)return say('اختر مادة واحدة على الأقل للمدرس.');if(ph&&!/^01[0125]\d{8}$/.test(ph))return say('رقم الموبايل غير صحيح.');if(pw&&!ph)return say('اكتب رقم موبايل المدرس.');if(pw&&pw.length<6)return say('كلمة السر 6 أحرف على الأقل.');
  b.disabled=true;say('جارٍ الإنشاء...');let im;try{im=await up('ntif','teachers')||fv('nti')||null}catch(_){b.disabled=false;return say(UPERR)}
  if(ph&&pw){const k=await mkAcc(ph,pw,n);if(k=='err'||k=='confirm'){b.disabled=false;return say(k=='confirm'?'الحساب يحتاج تفعيل — عطّل Confirm email من إعدادات Supabase Auth.':'تعذر إنشاء حساب المدرس — جرّب كلمة سر أقوى.')}}
  const r=await post('aa_edu_teachers',{name:n,name_en:fv('ntne')||null,slug:slg(fv('ntsl'))||slg(fv('ntne')),subject_ids:chk('nsc'),...(lids('nlc','nsc').length?{lesson_ids:lids('nlc','nsc')}:{}),bio:fv('ntb')||null,image:im},'return=representation');if(!r.ok){b.disabled=false;return fail(r)}
  const t=(await r.json())[0];let m='تمت إضافة المدرس';
  if(ph){const r2=await post('rpc/edu_set_staff',{p_ident:ph,p_role:'teacher',p_teacher:t.id}),x=r2.ok?await r2.json():'تعذر الربط';m=x=='تم'?'تمت إضافة المدرس وربط حسابه':'تمت إضافة المدرس لكن: '+x}
  return run(r,m)}
 if(a=='saveab'){const pu=fv('abu');if(pu&&!/^https?:\/\//i.test(pu))return say('رابط الصفحة لازم يبدأ بـ https://');b.disabled=true;say('جارٍ الحفظ...');let ph;try{ph=await up('abpf','about')||fv('abp')||null}catch(_){b.disabled=false;return say(UPERR)}
  const body={id:1,platform_title:fv('abpt')||null,platform_text:$('#abpx').value.trim()||null,name:fv('abn')||null,role_title:fv('abr')||null,bio:$('#abb').value.trim()||null,photo:ph,experience:$('#abe').value.trim()||null,page_url:pu||null,page_label:fv('abl')||null,socials:$('#abs').value.trim()||null,updated_at:new Date().toISOString()};
  const r=await post('aa_edu_about?on_conflict=id',body,'resolution=merge-duplicates,return=minimal');b.disabled=false;if(!r.ok)return say('تعذر الحفظ — شغّل setup_about.sql وتأكد إن حسابك أدمن.');AB={...AB,...body};ABerr=false;draw();return say('تم حفظ صفحة عن المنصة')}
 if(a=='lnk'){const ph=nph(prompt('رقم موبايل حساب المدرس (لازم يكون مسجّل في الموقع)')||'');if(!ph)return;const r=await post('rpc/edu_set_staff',{p_ident:ph,p_role:'teacher',p_teacher:+id}),x=r.ok?await r.json():'تعذر الربط — شغّل setup_admin_panel.sql';if(x!='تم')return say(x);return run(r,'تم ربط الحساب')}
 if(a=='ban'){const on=b.dataset.b=='1',rs=on?prompt('سبب الحظر (اختياري)'):'';if(on&&rs===null)return;if(!on&&!confirm('فك الحظر عن هذا المستخدم؟'))return;const r=await post('rpc/edu_set_ban',{p_user:id,p_ban:on,p_reason:rs||null}),x=r.ok?await r.json():'تعذر التنفيذ — شغّل setup_admin_v5.sql';if(x!='تم')return say(x);const r2=await post('rpc/edu_admin_users',{});us=r2.ok?await r2.json():us;draw();return say(on?'تم الحظر':'تم فك الحظر')}
 if(a=='tks'){TKS=+id;TKM=[];draw();TKM=await get('aa_edu_ticket_messages?ticket_id=eq.'+TKS+'&order=created_at').catch(()=>[]);return draw()}
 if(a=='tkb'){TKS=0;return draw()}
 if(a=='tkf'){TKF=b.dataset.f;return draw()}
 if(a=='tkr'){const t=fv('tkt');if(t.length<2)return say('اكتب الرد أولًا.');b.disabled=true;const r=await post('aa_edu_ticket_messages',{ticket_id:TKS,sender_id:U().id,body:t});if(!r.ok){b.disabled=false;return say('تعذر إرسال الرد.')}await loadTab();draw();return say('تم إرسال الرد وإشعار الطالب')}
 if(a=='tkst')return run(await rest('aa_edu_tickets?id=eq.'+id,{method:'PATCH',body:JSON.stringify({status:b.dataset.s})}),'تم تحديث حالة التذكرة');
 if(a=='tkd'&&confirm('حذف التذكرة نهائيًا؟')){TKS=0;return run(await rest('aa_edu_tickets?id=eq.'+id,{method:'DELETE'}),'تم حذف التذكرة')}
 if(a=='sjf'){const x=id?subs.find(y=>y.id==id):{name:'',icon:'book',color:'#0878C9'};
  const ok=await modal(id?'تعديل المادة':'إضافة مادة',`<label>اسم المادة</label><input id="sn" value="${esc(x.name)}" maxlength="60"><label>الرابط بالإنجليزي (مثال: math) — يظهر في الرابط courses#course-math</label><input id="ssl" dir="ltr" value="${esc(x.slug||'')}" maxlength="40" placeholder="math"><div class="g2"><div><label>الأيقونة</label><select id="si">${Object.entries(ICL).map(([k,v])=>`<option value="${k}" ${k==x.icon?'selected':''}>${v}</option>`).join('')}</select></div><div><label>اللون</label><input id="sc" type="color" value="${x.color||'#0878C9'}"></div></div>`,async()=>{const n=fv('sn');if(n.length<2){say('اكتب اسم المادة.');return false}
   const body={name:n,icon:$('#si').value,color:$('#sc').value},sl=slg(fv('ssl'));if(sl||!id)body.slug=sl;const r=id?await rest('aa_edu_subjects?id=eq.'+id,{method:'PATCH',body:JSON.stringify(body)}):await post('aa_edu_subjects',{...body,grade:'prep3',sort:subs.length+1});if(!r.ok){await fail(r);return false}});
  if(ok){await loadTab();draw();say('تم الحفظ')}return}
 if(a=='sjd'&&confirm('حذف المادة؟ لازم تكون فاضية من الدروس.'))return run(await rest('aa_edu_subjects?id=eq.'+id,{method:'DELETE'}),'تم حذف المادة');
 if(a=='movs')return move(subs.slice().sort(bySort),id,+b.dataset.d,'aa_edu_subjects');
 if(a=='uf'){if(!ts.length)ts=await LK('aa_edu_teachers?order=id').catch(()=>[]);const x=us.find(y=>y.id==id),k=stf.find(y=>y.user_id==id),cur=k?k.role:'';
  const ok=await modal('تعديل المستخدم',`<label>الاسم</label><input id="un1" value="${esc(x.name||'')}" maxlength="60"><div class="g2"><div><label>النقاط</label><input id="up1" type="number" min="0" value="${x.points||0}"></div><div><label>الصلاحية</label><select id="ur1"><option value="">طالب</option><option value="teacher" ${cur=='teacher'?'selected':''}>مدرس</option><option value="admin" ${cur=='admin'?'selected':''}>أدمن</option></select></div></div><div id="utw" ${cur=='teacher'?'':'hidden'}><label>المدرس المرتبط</label>${sel2('ut1',ts,t=>esc(t.name),k&&k.teacher_id)}</div>`,async()=>{
   const r=await rest('aa_edu_profiles?id=eq.'+id,{method:'PATCH',body:JSON.stringify({name:fv('un1'),points:Math.max(0,+fv('up1')||0)})});if(!r.ok){say(SQLERR);return false}
   const ro=$('#ur1').value;if(ro!=cur){const r2=ro?await post('rpc/edu_set_staff',{p_ident:x.phone,p_role:ro,p_teacher:ro=='teacher'?+$('#ut1').value:null}):await post('rpc/edu_remove_staff',{p_user:id}),m=r2.ok?await r2.json():'تعذر تغيير الصلاحية';if(m!='تم'){say(m);return false}}});
  if(ok){await loadTab();draw();say('تم حفظ المستخدم')}return}
 if(a=='nts'){const t=fv('nt1');if(t.length<2)return say('اكتب عنوان الإشعار.');let uid=null;
  if($('#nau').value=='one'){const q=fv('nus'),m=us.find(u=>(u.name||'')+' - '+(u.phone||'')==q)||us.find(u=>u.phone&&nph(q)==u.phone);if(!m)return say('اختر مستخدمًا من القائمة.');uid=m.id}
  b.disabled=true;const r=await post('aa_edu_notifications',{user_id:uid,title:t,body:fv('nb1')||null,link:fv('nl1')||null});if(!r.ok){b.disabled=false;return say(SQLERR)}return run(r,uid?'تم إرسال الإشعار للمستخدم':'تم إرسال الإشعار لكل الطلاب')}
 if(a=='ntd'&&confirm('حذف الإشعار؟ سيختفي من عند الطلاب.'))return run(await rest('aa_edu_notifications?id=eq.'+id,{method:'DELETE'}),'تم حذف الإشعار');
 if(a=='qs'){const t=($('#qa'+id).value||'').trim();if(!t)return say('اكتب الرد أولًا.');return run(await rest('aa_edu_questions?id=eq.'+id,{method:'PATCH',body:JSON.stringify({answer:t})}),'تم إرسال الرد وإشعار الطالب')}
 if(a=='qd'&&confirm('حذف السؤال؟'))return run(await rest('aa_edu_questions?id=eq.'+id,{method:'DELETE'}),'تم حذف السؤال');
 if(a=='rvd'&&confirm('حذف التقييم؟'))return run(await rest('aa_edu_reviews?id=eq.'+id,{method:'DELETE'}),'تم حذف التقييم');
 if(a=='eq'){const z=qzs.find(y=>y.id==id),r=await get('aa_edu_quiz_questions?quiz_id=eq.'+id+'&order=sort').catch(()=>[]);QT=z.title;QI=r.map(x=>{const o=x.options.slice();while(o.length<4)o.push('');return{q:x.q,o,a:x.answer}});if(!QI.length)QI=[blank()];P={id:z.course_id,k:'q',qid:+id};return draw()}
 if(a=='op'){P={id:+id,k:b.dataset.k};if(P.k=='q'){QI=[blank()];QT=''}return draw()}
 if(a=='addq'){collect();QI.push(blank());return draw()}
 if(a=='delq'){collect();QI.splice(+b.dataset.i,1);return draw()}
 if(a=='saveq'){collect();if(QT.trim().length<2)return say('اكتب عنوان الاختبار.');
  const rows=[];for(const [n,x] of QI.entries()){const o=x.o.map(s=>s.trim()),ok=o.filter(Boolean);if(x.q.trim().length<2||ok.length<2||!o[x.a])return say('السؤال '+(n+1)+': اكتب السؤال واختيارين على الأقل، وحدد إجابة صحيحة مكتوبة.');
   rows.push({q:x.q.trim(),options:ok,answer:ok.indexOf(o[x.a]),sort:n+1})}
  b.disabled=true;const r=await post('aa_edu_quizzes',{course_id:P.id,title:QT.trim()},'return=representation');if(!r.ok){b.disabled=false;return say('تعذر الحفظ — شغّل setup_uploads.sql.')}
  const z=(await r.json())[0];const r2=await post('aa_edu_quiz_questions',rows.map(x=>({...x,quiz_id:z.id})));if(!r2.ok){await rest('aa_edu_quizzes?id=eq.'+z.id,{method:'DELETE'});b.disabled=false;return say('تعذر حفظ الأسئلة.')}
  if(P.qid)await rest('aa_edu_quizzes?id=eq.'+P.qid,{method:'DELETE'});return run(r2,'تم حفظ الاختبار')}
 if(a=='delz'&&confirm('حذف الاختبار؟'))return run(await rest('aa_edu_quizzes?id=eq.'+id,{method:'DELETE'}));
 // دروس
 if(a=='rnl'){const l=ls.find(x=>x.id==id),t=prompt('عنوان الدرس',l.title);if(!t||t.trim().length<2)return;const un=prompt('الوحدة (اتركها فاضية لو مفيش)',l.unit||'');if(un===null)return;const sl=prompt('الرابط بالإنجليزي slug (تغييره بيغيّر رابط الدرس)',l.slug||'');if(sl===null)return;const nb={title:t.trim(),unit:un.trim()||null};if(slg(sl))nb.slug=slg(sl);return run(await rest('aa_edu_lessons?id=eq.'+id,{method:'PATCH',body:JSON.stringify(nb)}))}
 if(a=='movl'){const l=ls.find(x=>x.id==id);return move(ls.filter(x=>x.subject_id==l.subject_id).sort(bySort),id,+b.dataset.d,'aa_edu_lessons')}
 if(a=='dell'&&confirm('حذف الدرس؟'))return run(await rest('aa_edu_lessons?id=eq.'+id,{method:'DELETE'}));
 // كورسات
 if(a=='movc'){const c=cs.find(x=>x.id==id);return move(cs.filter(x=>x.lesson_id==c.lesson_id).sort(bySort),id,+b.dataset.d,'aa_edu_courses')}
 if(a=='savec'){const c=cs.find(x=>x.id==id);if(fv('cn').length<2)return say('اكتب عنوان الكورس.');b.disabled=true;say('جارٍ الحفظ... لا تغلق الصفحة');let img,vid;try{img=await up('cif','covers')||fv('ci')||null;vid=await up('cvf','videos')||fv('cv')||null}catch(_){b.disabled=false;return say(UPERR)}vid=flagU(vid,'#cne')||null;
  const body={lesson_id:+fv('cl'),title:fv('cn'),description:fv('cd')||null,image:img,video_url:vid,is_free:$('#cf').checked};if(R=='admin'&&$('#ct'))body.teacher_id=+fv('ct');
  const r=await rest('aa_edu_courses?id=eq.'+id,{method:'PATCH',body:JSON.stringify(body)});if(!r.ok){b.disabled=false;return say(SQLERR)}
  if(R=='admin'&&$('#cfe')&&$('#cfe').checked!=!!c.is_featured)await rest('aa_edu_courses?id=eq.'+id,{method:'PATCH',body:JSON.stringify({is_featured:$('#cfe').checked})});
  return run(r,'تم حفظ التعديلات')}
 if(a=='delc'&&confirm('حذف الكورس وكل ملفاته واختباراته؟')){await rest('aa_edu_course_files?course_id=eq.'+id,{method:'DELETE'});await rest('aa_edu_course_solutions?course_id=eq.'+id,{method:'DELETE'});return run(await rest('aa_edu_courses?id=eq.'+id,{method:'DELETE'}))}
 if(a=='savep'){const t=fv('pt');if(t.length<2)return say('اكتب العنوان.');b.disabled=true;say('جارٍ الرفع... لا تغلق الصفحة');let u;try{u=await up('pf',P.k!='s'?'files':'solutions')||fv('pl')}catch(_){b.disabled=false;return say(UPERR)}if(P.k=='s')u=flagU(u,'#pne');
  if(!u){b.disabled=false;return say('ارفع ملفًا أو الصق رابطًا.')}
  return run(await post(P.k!='s'?'aa_edu_course_files':'aa_edu_course_solutions',P.k!='s'?{course_id:P.id,title:t,url:u,kind:P.k=='m'?'summary':/\.(png|jpe?g|webp|gif)$/i.test(u)?'image':'pdf'}:{course_id:P.id,title:t,video_url:u}),'تمت الإضافة')}
 if(a=='rns'||a=='rnf'){const x=(a=='rns'?sols:fls).find(y=>y.id==id),t=prompt('العنوان',x.title);if(t&&t.trim().length>1)return run(await rest((a=='rns'?'aa_edu_course_solutions':'aa_edu_course_files')+'?id=eq.'+id,{method:'PATCH',body:JSON.stringify({title:t.trim()})}));return}
 if(a=='dels'&&confirm('حذف فيديو الحل؟'))return run(await rest('aa_edu_course_solutions?id=eq.'+id,{method:'DELETE'}));
 if(a=='delf'&&confirm('حذف الملف؟'))return run(await rest('aa_edu_course_files?id=eq.'+id,{method:'DELETE'}));
 // مدرسون
 if(a=='savet'){if(fv('tn').length<2)return say('اكتب اسم المدرس.');if(!chk('tsc').length)return say('اختر مادة واحدة على الأقل للمدرس.');b.disabled=true;let im;try{im=await up('tif','teachers')||fv('ti')||null}catch(_){b.disabled=false;return say(UPERR)}
  return run(await rest('aa_edu_teachers?id=eq.'+id,{method:'PATCH',body:JSON.stringify({name:fv('tn'),name_en:fv('tne')||null,...(slg(fv('tsl'))||slg(fv('tne'))?{slug:slg(fv('tsl'))||slg(fv('tne'))}:{}),subject_ids:chk('tsc'),...(lids('tlc','tsc').length||'lesson_ids' in (ts.find(x=>x.id==id)||{})?{lesson_ids:lids('tlc','tsc')}:{}),bio:fv('tb')||null,image:im})}),'تم حفظ المدرس')}
 if(a=='delt'&&confirm('حذف المدرس؟ لو عنده كورسات ممكن الحذف يفشل — انقل كورساته لمدرس آخر أولًا.'))return run(await rest('aa_edu_teachers?id=eq.'+id,{method:'DELETE'}));
 // تقديمات
 if(a=='apf'){if(b.dataset.s)apS=b.dataset.s;if(b.dataset.k)apK=b.dataset.k;return draw()}
 if(a=='apr'){const n=(($('#apn'+id)||{}).value||'').trim(),st=b.dataset.s;if(st=='rejected'&&n.length<3)return say('اكتب سبب الرفض ليظهر للطالب.');return run(await rest('aa_edu_applications?id=eq.'+id,{method:'PATCH',body:JSON.stringify({status:st,admin_note:n||null})}),st=='approved'?'تم القبول وإشعار الطالب':st=='rejected'?'تم الرفض وإشعار الطالب':'تمت إعادة التقديم للمراجعة')}
 if(a=='apd'&&confirm('حذف التقديم نهائيًا؟'))return run(await rest('aa_edu_applications?id=eq.'+id,{method:'DELETE'}),'تم الحذف');
 // إعلانات
 if(a=='adda'){b.disabled=true;say('جارٍ الرفع...');let u;try{u=await up('aif','ads')||fv('ai')}catch(_){b.disabled=false;return say(UPERR)}if(!u){b.disabled=false;return say('ارفع صورة أو ضع رابطها.')}
  return run(await post('aa_edu_ads',{title:fv('at1'),image:u,link:fv('al')||null,sort:ads.length+1}))}
 if(a=='savea'){b.disabled=true;let u;try{u=await up('aif','ads')||fv('ai')}catch(_){b.disabled=false;return say(UPERR)}if(!u){b.disabled=false;return say('ارفع صورة أو ضع رابطها.')}
  return run(await rest('aa_edu_ads?id=eq.'+id,{method:'PATCH',body:JSON.stringify({title:fv('at1'),image:u,link:fv('al')||null})}))}
 if(a=='tga'){const x=ads.find(y=>y.id==id);return run(await rest('aa_edu_ads?id=eq.'+id,{method:'PATCH',body:JSON.stringify({active:!x.active})}))}
 if(a=='mova')return move(ads.slice().sort(bySort),id,+b.dataset.d,'aa_edu_ads');
 if(a=='dela'&&confirm('حذف الإعلان؟'))return run(await rest('aa_edu_ads?id=eq.'+id,{method:'DELETE'}));
 // كتب
 if(a=='addb'||a=='saveb'){if(fv('bt').length<2)return say('اكتب عنوان الكتاب.');b.disabled=true;say('جارٍ الرفع... لا تغلق الصفحة');let u,cv;try{u=await up('bff','books')||fv('bu')||null;cv=await up('bcf','covers')||fv('bc')||null}catch(_){b.disabled=false;return say(UPERR)}
  const body={title:fv('bt'),subject:fv('bs')||null,url:u,cover:cv};return run(a=='addb'?await post('aa_edu_books',body):await rest('aa_edu_books?id=eq.'+id,{method:'PATCH',body:JSON.stringify(body)}),'تم')}
 if(a=='delb'&&confirm('حذف الكتاب؟'))return run(await rest('aa_edu_books?id=eq.'+id,{method:'DELETE'}));
 // تحديثات
 if(a=='addu'||a=='saveu'){if(fv('ut').length<2)return say('اكتب العنوان.');const body={title:fv('ut'),body:fv('ub')||null};return run(a=='addu'?await post('aa_edu_updates',body):await rest('aa_edu_updates?id=eq.'+id,{method:'PATCH',body:JSON.stringify(body)}),'تم')}
 if(a=='delu'&&confirm('حذف التحديث؟'))return run(await rest('aa_edu_updates?id=eq.'+id,{method:'DELETE'}));
});
/* تحديث فوري: بيجيب بيانات الصفحة المفتوحة بس، ومبيعملش حاجة لو إنت بتكتب أو فاتح نافذة */
const busy=()=>P||document.querySelector('#md')||/^(INPUT|TEXTAREA|SELECT)$/.test((document.activeElement||{}).tagName);
setInterval(async()=>{if(R!='admin'||document.hidden||!['s','ap'].includes(tab)||busy())return;try{await loadTab();draw()}catch(_){}},60000);
onLive(async()=>{if(!R||tab=='o'||Date.now()-(window._ownW||0)<4000||busy())return;try{await loadTab();draw()}catch(_){}});
document.addEventListener('change',async e=>{const i=e.target;
 if(i.id=='nau'){const w=$('#nuw');if(w)w.hidden=i.value!='one';if(i.value=='one'&&!usFull){try{us=await J('edu_admin_users');usFull=true;const d=$('#nul');if(d)d.innerHTML=us.map(u=>`<option value="${esc((u.name||'')+' - '+(u.phone||''))}">`).join('')}catch(_){say('تعذر تحميل المستخدمين')}}}
 if(i.id=='ur1'){const w=$('#utw');if(w)w.hidden=i.value!='teacher'}});
new MutationObserver(()=>{const k=document.querySelector('.ktabs'),b=k&&k.querySelector('a.on');if(k&&b&&k.scrollWidth>k.clientWidth+2)k.scrollLeft=b.offsetLeft-(k.clientWidth-b.offsetWidth)/2}).observe(document.getElementById('o'),{childList:true});
(async()=>{const sk='acad_stf:'+(U()||{}).id;let s=null;try{s=JSON.parse(sessionStorage.getItem(sk)||'null')}catch(_){}
 try{if(!s){const r=await get('aa_edu_staff?select=role,teacher_id');s=r[0]||null;if(s)try{sessionStorage.setItem(sk,JSON.stringify(s))}catch(_){}}}catch(_){return $('#o').innerHTML='<p class="empty">تعذر التحميل.</p>'}
 if(!s)return $('#o').innerHTML='<p class="empty">هذه الصفحة للمدرسين والإدارة فقط.</p><div class="box" style="max-width:380px;margin:16px auto;text-align:center"><b>عندك حساب إدارة؟</b><p class="muted">سجّل خروج ثم ادخل برقم موبايل وكلمة سر حساب الأدمن.</p><button class="btn btn-p btn-s" onclick="setU(null);location.href=\'/auth#login\'">تسجيل الدخول بحساب الإدارة</button></div>';
 R=s.role;TID=s.teacher_id;
 if(R!='admin'&&!['c','qa'].includes(tab)){location.replace(TURL.c);return}
 document.querySelector('h1').innerHTML=ic(R=='admin'?'crown':'cap',26)+(R=='admin'?' لوحة الإدارة':' لوحة المدرس');
 draw();const nm=(document.querySelector('.ktabs a.on')||{}).textContent;if(nm)document.title=nm+' | '+(R=='admin'?'لوحة الإدارة':'لوحة المدرس');
 try{await loadTab()}catch(_){BOOT=false;draw();$('#o').insertAdjacentHTML('beforeend','<p class="empty">تعذر تحميل بيانات الصفحة — حدّث الصفحة.</p>');return}
 BOOT=false;draw()})();
